// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// ExtendedTime is an autogenerated mock type for the ExtendedTime type
type ExtendedTime struct {
	mock.Mock
}

// findDaily provides a mock function with given fields: w, ticker, interval
func (_m *ExtendedTime) findDaily(w http.ResponseWriter, ticker string, interval string) {
	_m.Called(w, ticker, interval)
}

// findMonthly provides a mock function with given fields: w, ticker, interval
func (_m *ExtendedTime) findMonthly(w http.ResponseWriter, ticker string, interval string) {
	_m.Called(w, ticker, interval)
}

// findWeekly provides a mock function with given fields: w, ticker, interval
func (_m *ExtendedTime) findWeekly(w http.ResponseWriter, ticker string, interval string) {
	_m.Called(w, ticker, interval)
}
