// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// ExtendedTimeStock is an autogenerated mock type for the ExtendedTimeStock type
type ExtendedTimeStock struct {
	mock.Mock
}

// FindTimeSeriesByTicker provides a mock function with given fields: w, r
func (_m *ExtendedTimeStock) FindTimeSeriesByTicker(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
