// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// Intraday is an autogenerated mock type for the Intraday type
type Intraday struct {
	mock.Mock
}

// findFifteenMin provides a mock function with given fields: w, ticker, interval
func (_m *Intraday) findFifteenMin(w http.ResponseWriter, ticker string, interval string) {
	_m.Called(w, ticker, interval)
}

// findFiveMin provides a mock function with given fields: w, ticker, interval
func (_m *Intraday) findFiveMin(w http.ResponseWriter, ticker string, interval string) {
	_m.Called(w, ticker, interval)
}

// findOneMin provides a mock function with given fields: w, ticker, interval
func (_m *Intraday) findOneMin(w http.ResponseWriter, ticker string, interval string) {
	_m.Called(w, ticker, interval)
}

// findSixtyMin provides a mock function with given fields: w, ticker, interval
func (_m *Intraday) findSixtyMin(w http.ResponseWriter, ticker string, interval string) {
	_m.Called(w, ticker, interval)
}

// findThirtyMin provides a mock function with given fields: w, ticker, interval
func (_m *Intraday) findThirtyMin(w http.ResponseWriter, ticker string, interval string) {
	_m.Called(w, ticker, interval)
}
