// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// IntradayStock is an autogenerated mock type for the IntradayStock type
type IntradayStock struct {
	mock.Mock
}

// FindIntradayTimeSeriesByTicker provides a mock function with given fields: w, r
func (_m *IntradayStock) FindIntradayTimeSeriesByTicker(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
