// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// Quote is an autogenerated mock type for the Quote type
type Quote struct {
	mock.Mock
}

// FindQuote provides a mock function with given fields: w, r
func (_m *Quote) FindQuote(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
