// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	apiresponses "github.com/stock-details-api/internal/services/stocks/models/apiresponses"
	mock "github.com/stretchr/testify/mock"
)

// Search is an autogenerated mock type for the Search type
type Search struct {
	mock.Mock
}

// FindClosestMatch provides a mock function with given fields: search
func (_m *Search) FindClosestMatch(search string) apiresponses.BestMatchResponse {
	ret := _m.Called(search)

	var r0 apiresponses.BestMatchResponse
	if rf, ok := ret.Get(0).(func(string) apiresponses.BestMatchResponse); ok {
		r0 = rf(search)
	} else {
		r0 = ret.Get(0).(apiresponses.BestMatchResponse)
	}

	return r0
}
